spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        default_batch_fetch_size: 20
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
logging:
  level:
    org.hibernate: WARN
    org.springframework.transaction: DEBUG

