version: "3.8"

services:

  mongodb:
    image: mongo:latest
    container_name: hw17-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hw17-docker:latest
    container_name: hw17-shell-app
    stdin_open: true
    tty: true
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/maindb
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
